### PR TITLE
Nesting middleware context

### PR DESCRIPTION
**Pull request by FedorLap2006**
This PR contains a fix/implementation for nesting middleware contexts, so when this middleware is being invoked under the top-level middleware it would capture the context and won't duplicate a span

### CODE REVIEW

**Comment by FedorLap2006** [comment]
I don't really know why it is showing already merged commits, but well, at least it's working

**Comment by psmarcin** [comment]
Is there any change to write unit tests for that?

**Comment by FedorLap2006** [comment]
Hmm, sure.

**Comment by psmarcin** [comment]
@FedorLap2006 are you still interested in this PR?

**Comment by FedorLap2006** [comment]
> @FedorLap2006 are you still interested in this PR?

Oh yeah, I just kinda forgot about it

**Pull request closed without merging**
